#!/bin/bash
if [ -z "$1" ]; then
  echo "Usage: <version, no prefix>"
  exit 1
fi

set -ex

version="$1"
current="$(git rev-parse --abbrev-ref HEAD)"
branch="release-$version"
tag="v$version"
license=license.md

git checkout -b "$branch" master
sed --in-place "s/Development Draft/$version/" "$license"
sed --in-place "s/{version}/$version/" "$license"
git add "$license"
git commit -m "Version $version"
git tag "$tag"
git push origin "$branch"
git push origin "$tag"
git checkout "$current"
